<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>BilibiliUploader</AssemblyName>
    <Version>1.1.0</Version>
    <Deterministic>true</Deterministic>
    <PathMap>$(MSBuildProjectDirectory)=/_/src</PathMap>
    <DebugType>None</DebugType>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <RuntimeFrameworkVersion>8.0.31</RuntimeFrameworkVersion>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
    <AllowUnsafeBlocks>false</AllowUnsafeBlocks>
    <EnableUnsafeBinaryFormatterSerialization>false</EnableUnsafeBinaryFormatterSerialization>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.4258.31" />
    <Compile Remove="tests\**" />
  </ItemGroup>
  <Target Name="RemoveUnusedWpf" BeforeTargets="ResolveAssemblyReferences">
    <ItemGroup>
      <Reference Remove="@(Reference)" Condition="'%(Reference.Filename)' == 'Microsoft.Web.WebView2.Wpf'" />
    </ItemGroup>
  </Target>
</Project>
